import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { CartProvider } from './providers/CartProvider';
import Header from './components/Header';
import './globals.css';
import { WishlistProvider } from "./providers/WishlistProvider";

import { Almarai } from 'next/font/google';

const almarai = Almarai({
  subsets: ['arabic'],
  weight: ['300', '400', '700', '800'], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={almarai.className}>

        <body className={`  min-h-screen`}>
          <CartProvider>
            <WishlistProvider>
              <Header />
              <main className="container mx-auto px-4 py-8">
                {children}
              </main>
              <ToastContainer position="bottom-right" />
            </WishlistProvider>
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
