import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { CartProvider } from './providers/CartProvider';
import Header from './components/Header';
import './globals.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      
    <body className={`  bg-gray-50 min-h-screen`}>
    <CartProvider>
          <Header />
          <main className="container mx-auto px-4 py-8">
            {children}
          </main>
          <ToastContainer position="bottom-right" />
        </CartProvider>
      </body>
    </html>
  </ClerkProvider>
  );
}
